# Store database connection information here and rename this file to config.yml 
default:
  dbInfo:
    host: 'localhost'
    port: '3306'
    user: 'dbuser'
    password: 'dbpassword'
    database: 'qrchem'
    dataTable: 'ExpData'
    courseTable: 'Courses'
    semesterTable: 'Semesters'
    userPinTable: 'UserPins'
    
  # LLM model API keys
  llmKeys:
    gemini: 'YOUR_API_KEY_HERE'
    openai: 'sk-YOUR_API_KEY_HERE'
    deepseek: 'sk-YOUR_API_KEY_HERE'
